name: Data node

on: push

env:
  ERL_AFLAGS: "-enable-feature all"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:27
    defaults:
      run:
        working-directory: ./cli
    steps:
      - uses: actions/checkout@v3
        with:
          otp-version: '26'
          rebar3-version: '3.22.1'
      - name: Lint
        run: rebar3 lint
      - name: Run tests
        run: rebar3 eunit -v